import { ENV_FILENAME } from "./compose-base";
import type { RenderPlan } from "./plan";

const HEADER = `# ${ENV_FILENAME}
#
# Generated by \`ojuri render\`. Do not edit: the next render overwrites
# it. Change ojuri.yaml instead.
#
# These are the variables Compose substitutes that the manifest
# controls. Everything else stays in your own .env, which this does not
# touch. Pass both files to Compose, this one last so it wins:
#
#   docker compose --env-file .env --env-file .ojuri/${ENV_FILENAME} ...
#
# \`ojuri up\` does that for you.
`;

export function renderEnvFile(plan: RenderPlan): string {
  const lines = [HEADER];
  for (const [key, value] of Object.entries(plan.env)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  return lines.join("\n");
}
