import { OVERLAY_FILENAME } from "./compose-base";
import type { ComposeOverlay, ComposeServiceOverride, RenderPlan } from "./plan";

const HEADER = `# ${OVERLAY_FILENAME}
#
# Generated by \`ojuri render\`. Do not edit: the next render overwrites
# it. Change ojuri.yaml instead.
#
# Compose merges this over docker-compose.yml, so it only carries what
# the manifest changes. A manifest holding the compose defaults renders
# nothing here at all; the shipped one renders the nginx config that
# fronts Sentinel, and nothing else.
#
# \`!reset\` removes a key the base file set; \`!override\` replaces one
# rather than merging into it. Both need Compose 2.24 or newer, which is
# already the floor for docker-compose.ghcr.yml.
`;

/** Serialise the overlay. Written by hand because the Compose merge tags are not YAML the parser emits. */
export function renderOverlay(plan: RenderPlan): string {
  const lines: string[] = [HEADER];
  const entries = Object.entries(plan.overlay.services);

  if (entries.length === 0) {
    lines.push("# Nothing to override.", "services: {}", "");
    return lines.join("\n");
  }

  lines.push("services:");
  for (const [name, spec] of entries) {
    lines.push(...serviceLines(name, spec));
  }
  lines.push("");
  return lines.join("\n");
}

function serviceLines(name: string, spec: ComposeServiceOverride): string[] {
  if (spec.reset) return ["", `  ${name}: !reset null`];

  const lines: string[] = ["", `  ${name}:`];

  if (spec.dependsOn !== undefined) {
    if (spec.dependsOn === null || Object.keys(spec.dependsOn).length === 0) {
      lines.push("    depends_on: !override {}");
    } else {
      lines.push("    depends_on: !override");
      for (const [dep, condition] of Object.entries(spec.dependsOn)) {
        lines.push(`      ${dep}:`);
        lines.push(`        condition: ${condition}`);
      }
    }
  }

  if (spec.resetPorts) {
    lines.push("    ports: !reset null");
  } else if (spec.ports) {
    lines.push("    ports: !override");
    for (const port of spec.ports) lines.push(`      - ${scalar(port)}`);
  }

  if (spec.volumes) {
    lines.push("    volumes: !override");
    for (const volume of spec.volumes) lines.push(`      - ${scalar(volume)}`);
  }

  if (spec.image !== undefined) {
    lines.push(`    image: ${scalar(spec.image)}`);
  }

  if (spec.environment && Object.keys(spec.environment).length > 0) {
    lines.push("    environment:");
    for (const [key, value] of Object.entries(spec.environment)) {
      lines.push(`      ${key}: ${scalar(value)}`);
    }
  }

  const deploy = deployLines(spec);
  if (deploy.length > 0) {
    lines.push("    deploy:");
    lines.push(...deploy);
  }

  return lines;
}

function deployLines(spec: ComposeServiceOverride): string[] {
  const lines: string[] = [];
  if (spec.replicas !== undefined) lines.push(`      replicas: ${spec.replicas}`);
  if (spec.resources && (spec.resources.cpu || spec.resources.memory)) {
    lines.push("      resources:", "        limits:");
    if (spec.resources.cpu) lines.push(`          cpus: ${scalar(spec.resources.cpu)}`);
    if (spec.resources.memory) lines.push(`          memory: ${scalar(spec.resources.memory)}`);
  }
  return lines;
}

/** Always quote. Connection URLs carry colons and @, which bare YAML reads badly. */
function scalar(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function isNoOp(overlay: ComposeOverlay): boolean {
  return Object.keys(overlay.services).length === 0;
}
